version: "3.3"

services:

  api:
    container_name: api-gateway
    build:
      context: .
    image: moleculer/demo
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=80"
    networks:
      - internal

  # nats:
  #   container_name: transporter
  #   image: nats
  #   networks:
  #     - internal

  traefik:
    image: traefik
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal

networks:
  internal:

volumes:
  data:
